# Generated by Django 3.1.3 on 2020-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=280)),
            ],
        ),
    ]
